### PR TITLE
fix: youtube-dl not included in the AppImage

### PR DESCRIPTION
**Pull request by azubieta**

### CODE REVIEW

**Comment by ShrirajHegde** [comment]
where is the appimage? can you provide the link for that??

**Comment by g-fb** [comment]
There's one built when a new commit is pushed.
You can check them here https://github.com/g-fb/haruna/actions

But I don't test them and don't support them, meaning if something doesn't work with it I won't fix it myself.

**Comment by ShrirajHegde** [comment]
@azubieta is it possible to include breeze as well? Theming doesn't work.

image

**Comment by azubieta** [comment]
> @azubieta is it possible to include breeze as well? Theming doesn't work.

It's, the bundle will be a bit larger but the theme should work. Notice that setting a fixed theme will prevent you from using the system one.

**Comment by ShrirajHegde** [comment]
AppImage would be great for people who are trying it for the first time, they might want to try the dark mode. Assuming most people have breeze/any qt theme installed, any way to make theming work without including it??

**Comment by ShrirajHegde** [comment]
@azubieta

Youtube playback not working in fedora (on app image) any idea why?

**Comment by azubieta** [comment]
I'll have to investigate

**Comment by ShrirajHegde** [comment]
> I'll have to investigate


@azubieta 
any updates? it gives no warnings / errors
image


it gives no warnings / errors

image



just gets stuck here
Everything else works fine, it would be great to have appimage in the releases

**Comment by azubieta** [comment]
It seems we have an issue with the ssl certificates. openssl tried to load them from `/usr/lib/ssl/certs` but in Fedora they are store somewhere else.

**Comment by ShrirajHegde** [comment]
I think it's [here](https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/#:~:text=In%20Fedora%2C%20the%20consolidated%20system,%2Dtrust%2Dsource%2F%20directories.)

**Comment by azubieta** [comment]
Bot how can we tell to the openssl built for ubuntu that it should use those configurations ?

**Comment by ShrirajHegde** [comment]
how does it work in flatpak?

**Comment by ShrirajHegde** [comment]
https://gitlab.com/probono/platformissues/-/blob/master/README.md

This issue is discussed here, is it possible to include the certs in AppImage? because looking at the source above, this appimage will work only on Debian/ubuntu/gentoo

**Comment by azubieta** [comment]
> how does it work in flatpak?

Flatpack runs over a "runtime" which is a whole base system including openssl.


>  is it possible to include the certs in AppImage?

Yes, but they may get outdated. Ideally we would need to make an openssl conf capable of lading the certs from every distribution out there. I may need some help here.

**Comment by ShrirajHegde** [comment]
> > how does it work in flatpak?
> 
> Flatpack runs over a "runtime" which is a whole base system including openssl.
> 
> > is it possible to include the certs in AppImage?
> 
> Yes, but they may get outdated. Ideally we would need to make an openssl conf capable of lading the certs from every distribution out there. I may need some help here.

if this is the case, there should be a standard procedure to make Appimage work across distributions right? because I have seen too many appimages having problem with openssl

**Comment by ShrirajHegde** [comment]
check #66 please

**Pull request merged**
