### PR TITLE
Build and Upload Debian package to Release

### PR DESCRIPTION
**Pull request by ShrirajHegde**
ubuntu 20.04 requires KDE neon repos: (as mentioned in #52 )

```
sudo apt-key adv --keyserver 'https://archive.neon.kde.org/public.key' --recv-key E6D4736255751E5D
````

```
sudo add-apt-repository http://archive.neon.kde.org/user 
```

### CODE REVIEW

**Comment by g-fb** [comment]
Sorry, but I don't want to provide distro specific packages.

**Comment by ShrirajHegde** [comment]
> Sorry, but I don't want to provide distro specific packages.

any specific reason?

**Comment by g-fb** [comment]
Because then I have to test them and make sure they work and I don't want to do that.

**Comment by ShrirajHegde** [comment]
you can always only officially support flatpak.  My thought was that large flatpak downloads and updates inhibit discovery, 

When I first came across it, I wanted to try it out but didn't want to install it via flatpak, anyway it's better now since appimage with AppimageLauncher even makes file associations and desktop integration.

I kept searching mpv based players and wasn't satisfied with any, at least not compelling enough to ditch vlc. I would have settled way earlier if I could find a non-flatpak method. (I had tried compiling from source, but it wasn't working - dependency issues).

**Pull request closed without merging**
