### PR TITLE
Upload Appimage to Release

### PR DESCRIPTION
**Pull request by ShrirajHegde**
* Upload Appimage to Release
* AppImage usage instructions added to README

### CODE REVIEW

**Comment by g-fb** [comment]
Is the copyright correct for appimage-release.yml?
Where does the text "[Ship AppImage along with Flatpak](https://github.com/ShrirajHegde/haruna/releases)" come from?

**Comment by ShrirajHegde** [comment]
> Is the copyright correct for appimage-release.yml?

Ok I completely forgot about that, except for the lines 40 to 47 and line 33 to set release tag version, rest is the same as appimage.yml, what's the procedure of GPLv3? do I add modified date and my name or something?
> Where does the text "[Ship AppImage along with Flatpak](https://github.com/ShrirajHegde/haruna/releases)" come from?

I just added it manually, while tagging the release (to test). Action doesn't modify it

**Comment by ShrirajHegde** [comment]
> Is the copyright correct for appimage-release.yml?

I have removed the manually added text, if it's empty, it just shows the last commit message like this 
image

**Comment by g-fb** [comment]
> what's the procedure of GPLv3?

I don't really know either. I try to follow the REUSE Specification
See this question and decide if you want to add yourself as copyright holder https://reuse.software/faq/#when-copyright

If yes, just add another line under `SPDX-FileCopyrightText: 2021 Alexis Lopez Zubieta <contact@azubieta.net>` with your info.

**Comment by ShrirajHegde** [comment]
Should be okay now, I guess

https://spdx.github.io/spdx-spec/appendix-IX-file-tags/
https://api.kde.org/frameworks/kitemmodels/html/krearrangecolumnsproxymodel_8cpp_source.html
https://spdx.github.io/spdx-spec/4-file-information/#414-file-contributor

**Comment by ShrirajHegde** [comment]
@g-fb create a release to 0.6.3

**Pull request merged**
