### PR TITLE
Install .desktop file without the executable bit

### PR DESCRIPTION
**Pull request by lgbaldoni**

### CODE REVIEW

**Comment by g-fb** [comment]
Can you explain why?
I'm no cmake expert so I use KDE as reference and they use PROGRAMS.

**Comment by lgbaldoni** [comment]
As far as I know, freedesktop/xdg standards don't define permissions for .desktop files.

Cmake docs say:
```
The PROGRAMS form is identical to the FILES form except that the default permissions for the installed file also include OWNER_EXECUTE, GROUP_EXECUTE, and WORLD_EXECUTE. This form is intended to install programs that are not targets, such as shell scripts.
```

A .desktop is not a program nor it is a script. I checked my /usr/share/applications folder and every file is 644.

Could you show me the KDE example?

**Comment by g-fb** [comment]
https://invent.kde.org/kdevelop/kdevelop/-/blob/master/app/CMakeLists.txt#L99
https://invent.kde.org/multimedia/elisa/-/blob/master/CMakeLists.txt#L179
https://invent.kde.org/utilities/kate/-/blob/master/kate/CMakeLists.txt#L165
https://invent.kde.org/system/dolphin/-/blob/master/src/CMakeLists.txt#L413

**Comment by lgbaldoni** [comment]
I don't know what to say. I saw KDE's guidelines saying that it should be installed as executable, and I also see [this](https://cmake.org/cmake/help/v3.13/command/install.html#files).

I guess I can live with a local patch for the package.

**Comment by g-fb** [comment]
Asked in kde chat and seems to be a legacy thing.
I have changed the CMakeLists.txt  file though so this can't be merged anymore as is.
Let me know if you wanna fix it yourself or not.

**Pull request merged**
